server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: prodota318
    url: jdbc:mysql://localhost:3306/codejavadb
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
          dialect: org.hibernate.dialect.MySQL55Dialect
          format_sql: true
      show_sql: true